jobs:
  include:
    - language: php
      php:
        - 7.3
      services:
        - mysql
      cache:
        directories:
          - node_modules
          - vendor
      before_script:
        - cd ./tick-it-easy-backend
        - cp .env.travis .env
        - sudo mysql -e 'create database tick_it_easy;'
        - composer self-update
        - composer install --prefer-source --no-interaction --dev
        - php artisan key:generate
        - php artisan migrate
        - php artisan db:seed
        - php artisan serve
      script:
        - php artisan test --testsuite=Feature --stop-on-failure
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
            secure: "a+pPC17q932+zuTCnoAsvVLEqr8Q8elqnw1SUlR04Yh/Ha+ynfM/tAAw7Z0CrjkhPUgCE/Hb9c7aeXYXVgmEgCfLwiMX9/gEfg/s4n2eYMforECr5TA2wC902PGhcFu2WCEPPDyFUh1B9pIARBiYWGJCRDu5nGG+rh0X+8wz77+5vuSlBWUahdAKXgIaNdVHx7QkhiEnP3ALCNBa0mAhtrLPRgFDj2AIENIjK00e5NGjJ/+EVKw62cdanfpBCuJS+OTtAwln6jW5iS/zsLoqC6uDbGH2sIvcEziJ+ZND6SVHwbOEXBi0sp8bMUTUNFqoTLeAbPve9Du/bmWlmkRNyj7qa1/v0oswz/Myj+DZL4SEM+uwhnhVv/kQIQG+1BHindpyaaM1ZieFVonXVf5nSJbh697jUe72JHD4is7V+f00Vt/pYFwJUCvx6bgw2rbIORAr4hg8feTIz8H7443HAp9gwdcQRvGoUILPvS15oNHStb6Cx5fr3LVqoeuiIP/C69AUGvtGmv8dPmsn3R+KhCuYt4yaxme5oN3ZLduM6SYqs+a0K0OLooDu2OBDpXfGuNSlVW+TKP3UkZkV+CH7JE1GXIlp5VgQ8ArlbKIo1rVqh9GpURaTkjUMtloJMLIYk+YAjPCzuTPdkCjVpzqyUvuQdREHroXQ4MPCFzpCDWc="
        app: tick-it-easy-backend
        on:
          branch: main
        run: 
           - php artisan migrate --force

    - language: node_js
      node_js:
        - '12'

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable

      cache:
        directories:
          - ./node_modules
      before_script:
        - cd frontend
        - npm install
        - npm run build
      script:
        - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: "QV1um6DH8S+VkoJGtcWbVdG71Af6e8+uF4qrWIAQRVhL02joce3KMgvmKwzuQW8JQ2jngRPFSuC3Jq8VZsXeb4/d1lR8tRMxXnWhwZCfjDXaVLmkbfo3DfXuXO81t7oRb78+hsfE1IdrCZY5N9v+n+zyiPZ4SrCShZWlXnWLfG+KoqzA8VFZiPDZOju2gwT7XX1sIeUi1XvThccm6f/PHP4MBRz+sl2lhasvXXkltXsWmlj/XvQCBqPi6T1xsKy+x+rvqqFR9BopW8B+VlGGGoP0WsZ85VscP2J8XKs6VNHC5CARuSp8vDMVfUvdqbvsmmbQyVE4Brbc9g1NFyaXnS0XHZiz3VbM3r0/ei9q175NIrnrc57PhOJWw/zJ/cPEBQCPft7FFloKgWiU1w6HCmOoi+9las+9HWLWjW+wjFzXuovim3aBkdeimiilAtySZXDLBZhajKZqWhS664EBuJ6pFaNe9K3sf3eSUDnM+O12D+SJtN6K4ki3EpYHXw6KSUvw092ijYa4ocmYbxtkxsoJSQuyWgduOSPsHM7HaArj2kUIQQiyp52iC8Sr6mJCf+PexQJxF22fxpZBV3sxU7wqs/aqqBWlYAJKYeANsqiJJXabTYa6lJ0MduY97gdC4AFvEZ7GVrbt4n9d+VTR5LLijJY++mmhw7d5EgwAL8c="
        app: tick-it-easy-fe
        on:
          branch: main