jobs:
  include:
    - language: php
      php:
        - 7.3
      services:
        - mysql
      cache:
        directories:
          - node_modules
          - vendor
      before_script:
        - cd ./tick-it-easy-backend
        - cp .env.travis .env
        - sudo mysql -e 'create database tick_it_easy;'
        - composer self-update
        - composer install --prefer-source --no-interaction --dev
        - php artisan key:generate
        - php artisan migrate
        - php artisan db:seed
      script:
        - php artisan test 
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
            secure: "jorUspmxHg9urQ2+6u0cTM0seHh9X6Uncc5kUP05+/LbJeExCPGpb4n9OU7QmYrpOFrYA8nlTJ8zWdINTmAGksmk1gyXIHt/M+U0gquZxOPxAffAGKTrFPyX/fU+6qNp65jkVzRgIc918r7hJiZ2xLFYM22O9SCWWnMkrMJEVbEPNKO6J0WNpJFXOPGf0307KxYZyKjLXngbDr/4Uii6/Gk5RbJxh+JpoL0BDVjT9lFRL/KxuBOajR1kf4yhnm95AVXG2oXTMBx6o3+tvxNK8QAMX0tI3npDTq4QF0sSf1JeVo6rVuJaOHXjASD/E8poNREgyAXv+oTiFUVIIVIKek7OBKjJ3SK77RI/gSclQFHRRZ64BjmKHagjhK/loHOh/sxw/YMpfANcxCBnuxqTxqvg/+9MObvebWFiW0hZ7M4WLz4lI5ooqN2pc+RkZyPq2YEo3DvyT0zctUHIU4eSxw2VUmCIIncrUt4Thg0oAvM2PfN454kzpnFjwdKYkHJt/2VLb+HH5VlNE8djuTcwYxOsDaOZrWO53ezoNh8RkAtoFMDNpBel73rQZeBdx5wJn+KwBjNaUYEiNaVRzNSsxK5BQqRIyra07X6qezxc8cGfVpd37OpKAjT5t6ZyygnWArgbneE183VXTgsod+hAkX0tiJi0Jt+H118u0oyrosU="

        app: tick-it-easy-backend
        on:
          branch: main
        run: 
           - php artisan migrate --force

    - language: node_js
      node_js:
        - '12'

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable

      cache:
        directories:
          - ./node_modules
      before_script:
        - cd frontend
        - npm install
        - npm run build
      script:
        - npm run test -- --watch=false --no-progress --browsers=HeadlessChrome
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: "QV1um6DH8S+VkoJGtcWbVdG71Af6e8+uF4qrWIAQRVhL02joce3KMgvmKwzuQW8JQ2jngRPFSuC3Jq8VZsXeb4/d1lR8tRMxXnWhwZCfjDXaVLmkbfo3DfXuXO81t7oRb78+hsfE1IdrCZY5N9v+n+zyiPZ4SrCShZWlXnWLfG+KoqzA8VFZiPDZOju2gwT7XX1sIeUi1XvThccm6f/PHP4MBRz+sl2lhasvXXkltXsWmlj/XvQCBqPi6T1xsKy+x+rvqqFR9BopW8B+VlGGGoP0WsZ85VscP2J8XKs6VNHC5CARuSp8vDMVfUvdqbvsmmbQyVE4Brbc9g1NFyaXnS0XHZiz3VbM3r0/ei9q175NIrnrc57PhOJWw/zJ/cPEBQCPft7FFloKgWiU1w6HCmOoi+9las+9HWLWjW+wjFzXuovim3aBkdeimiilAtySZXDLBZhajKZqWhS664EBuJ6pFaNe9K3sf3eSUDnM+O12D+SJtN6K4ki3EpYHXw6KSUvw092ijYa4ocmYbxtkxsoJSQuyWgduOSPsHM7HaArj2kUIQQiyp52iC8Sr6mJCf+PexQJxF22fxpZBV3sxU7wqs/aqqBWlYAJKYeANsqiJJXabTYa6lJ0MduY97gdC4AFvEZ7GVrbt4n9d+VTR5LLijJY++mmhw7d5EgwAL8c="
        app: tick-it-easy-fe
        on:
          branch: main