jobs:
  include:
    - language: php
      php:
        - 7.3
      services:
        - mysql
      cache:
        directories:
          - node_modules
          - vendor
      before_script:
        - cd ./tick-it-easy-backend
        - cp .env.travis .env
        - sudo mysql -e 'create database tick_it_easy;'
        - composer self-update
        - composer install --prefer-source --no-interaction --dev
        - php artisan key:generate
        - php artisan migrate
        - php artisan db:seed
        - php artisan passport:keys
        - php artisan passport:client --personal 
      script:
        - php artisan test 
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
            secure: "Xq5UX9ec3OLcx3UO39wDejNxM6gpTEYGPUI3YxfWOoAuxh1krS3nvMMG3aXAZD+JSLXnYyd7S6JdfWUVocVlkxZPaje2EShyr/Ywx9m1ND+3KBp9j692jhWQaYBNG/gepp2XDxyB5cKiAHeyjuvW8wwaQfl8VN0CnpP16Kl1xkE/OE2CARJdKszFVFfGibDeS21y7AqyjZkZuCIeNmKksQSLjgl2hpqeAtJhRCB1ztuTMwEjx8k9MXAFHKJ4VopAyKU5QmojqqYU58UNrmxRy2bgKxUcifU+mSeJIHmfWzC3oaRcYl5V2gZYwBWwNXEWMIrn9inzkUgJgzhTu0VncIrYOTflz/7cGbCWgz4ISBHIYH2oj0lFou3kD65tegDILCE/4tu6Q/O0EaOQiAHClAKM+f4lnqhvims3bZo5lsFPDyXwuWNCEgQvwEc2ARc0JJMJEw30GRgvLvaBFegCWUSxAdoODFd9WHAf0KAFshRybEP4UCdP6S/NLnXZ941IwvI6omU6ZfwY13sigiyX7wV8Lbyy1b1ZyCQUyraPtdaHbZrqO8iEiRSXULky3T9RmmnKBpAEVRn6Jz28isTD0sDiBxLImzGOl3Rar89PzBdKKFLyxh4AXMKPgfL7BA7oqDfvGxaW5EfGkhiBCE4dFdFDJ+VSJK29HIlcDHBhZmI="

        app: tick-it-easy-backend
        on:
          branch: main
        run: 
           - php artisan migrate --force

    - language: node_js
      node_js:
        - '12'

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable

      cache:
        directories:
          - ./node_modules
      before_script:
        - cd frontend
        - npm install
        - npm run build
      script:
        - npm run test -- --watch=false --no-progress --browsers=HeadlessChrome
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: "t/iDGzr28+P7KjYy5ueoJifKhflN+JvryRbmBgzPe4QXbV1Ddk6tCA22Wtzc14b8FjL9L848LzlG7GNt0RGmk4wnhDawyaMf/7Jnf+MZLP3CpI1tSpJlopDzHn96/b58upev9Pj65Mb6nyoSi77ixHHh22uF/n9PrRt0DF15d1kXzyFR32lceEydUozQkTPRrjuG5JK+3nboh3T6EHGV2vwyJUC5yVL3rtXJzybYGkPYFATsf0XVkPn6/7k68DU9SMYUbnosrWjLUq6gQ9v2FVtkwgVPkZjEKkVsFZD20RBD+b25jBU5Pk3GIDocdLs2icmjeGYfpT60wWdi4/7sTTDTucB9uwx8xJdwS5kJxnrJVbEE6uzi1g3eSKMGuySAsfY+6Sg5L9l6ljJ10bzFWV4W7BuyLVOJCqALHTu2U+omrzCi2d2yL6qQkRi3V7BjA4yb2vq++UToshId4GMCURIUU3IvSRm4W2479tLvkdPAn1IChR4GCEPvXO42cjlmUrk1Z34kAVcMMey2wGTYefkjUzvjZcZSymGln3tApCBGpoOaWDH8cibdJ8AAflYQcjoSE/TnkZ0hopY/w/QBLynCE4slTlL24ZhDSkLMA/kiOCZ45dVkkTgLvDvlpjV18wXmOJJN6tJWhxgB64xh8BngJ1NuHD/F262I5J82dkg="
        app: tick-it-easy-fe
        on:
          branch: main