jobs:
  include:
    - language: php
      php:
        - 7.3
      services:
        - mysql
      cache:
        directories:
          - node_modules
          - vendor
      before_script:
        - cd ./tick-it-easy-backend
        - cp .env.travis .env
        - sudo mysql -e 'create database tick_it_easy;'
        - composer self-update
        - composer install --prefer-source --no-interaction --dev
        - php artisan key:generate
        - php artisan migrate
        - php artisan db:seed

      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
            secure: "wfnv0mZ7VogWHeJ/i64XLAgGnekVrL49Lt+ZYMCqBQksCHmHDFrWOenE0vwzdbZdI71tU6L6F5priRILBiHpte2auCnI5UWRYqJ//XJT+aPUvL7WkDFCa48xNfi7Osw9aw+UdbG+cZOF/GZmzZx7r7hEeOTb2U8I0q73X8TuaFT2yrdIu6wPN/+NXgSRRRDha7VvFUdA/aGO9z48qgoP320kBnAt23OqfTynMVq4gh6mTK7ZjgTnXFTgYrnlOIY/Wr8aieGB8ufoM+tG8VYsb+S+bJYIOWxFTeia7xlk+Z9qTkErblh66xiXiBWOUdCeY+pFt+UBRh3ICO4yBkshl+dctOgsO0gndWHq59vY4Sxuf/6labZ7DCf3aWom1Opkt+cffH1YSBSgbR4C2fFlKN/+hgYufxX8Slv/I0Cm44wNLuq4CPJge43JIOnLtnvdk2ybNXfVeZa/Fp+EinGq2GUs/ZuENA1RKFDwGGC3zX0pkkbQo9tnls79uWWbIy+NqSjkDw/ssFGnNU41UEZEvxch5U4WzGtC4fN6S92oNdQF48UjXQlW61zazMVHy/FZV+MHkHHX7a2ujElAJ4LFD6lidfIdLWaCWjPN6AUg86TovjfakqyI7McXfJtvwB8r6iwsV08A0G59deZYMoUZtgHRg8uQHEI0AqwmeLGy0Tw="
        app: tick-it-easy-backend
        on:
          branch: main

    - language: node_js
      node_js:
        - '12'

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable

      cache:
        directories:
          - ./node_modules
      before_script:
        - cd frontend
        - npm install
        - npm run build
      script:
        - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
         
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
            secure: "wfnv0mZ7VogWHeJ/i64XLAgGnekVrL49Lt+ZYMCqBQksCHmHDFrWOenE0vwzdbZdI71tU6L6F5priRILBiHpte2auCnI5UWRYqJ//XJT+aPUvL7WkDFCa48xNfi7Osw9aw+UdbG+cZOF/GZmzZx7r7hEeOTb2U8I0q73X8TuaFT2yrdIu6wPN/+NXgSRRRDha7VvFUdA/aGO9z48qgoP320kBnAt23OqfTynMVq4gh6mTK7ZjgTnXFTgYrnlOIY/Wr8aieGB8ufoM+tG8VYsb+S+bJYIOWxFTeia7xlk+Z9qTkErblh66xiXiBWOUdCeY+pFt+UBRh3ICO4yBkshl+dctOgsO0gndWHq59vY4Sxuf/6labZ7DCf3aWom1Opkt+cffH1YSBSgbR4C2fFlKN/+hgYufxX8Slv/I0Cm44wNLuq4CPJge43JIOnLtnvdk2ybNXfVeZa/Fp+EinGq2GUs/ZuENA1RKFDwGGC3zX0pkkbQo9tnls79uWWbIy+NqSjkDw/ssFGnNU41UEZEvxch5U4WzGtC4fN6S92oNdQF48UjXQlW61zazMVHy/FZV+MHkHHX7a2ujElAJ4LFD6lidfIdLWaCWjPN6AUg86TovjfakqyI7McXfJtvwB8r6iwsV08A0G59deZYMoUZtgHRg8uQHEI0AqwmeLGy0Tw="
        app: tick-it-easy-frontend
        on:
          branch: main
